### ISSUE TITLE
Assignment 2 ready for grading

### ISSUE THREAD

**Issue by alex-cox-gsd** [VIS-2129-F2020/alexcox-vis#1]
Hi all! My Assignment 2 HTML and RMD files are ready for grading, they are both called "Vis Week 2." Thank you!

**Comment by bauranov** [comment]
Really great work! I have nothing to add regarding the code. Initially, I couldn't find your assignment because it's named Assignment2 when it should be Assignment1. Please use the nomenclature from the syllabus. Additionally, make sure to assign me and Carole so your Assignment pops-up in our githubs. 

Keep up the good work!
